Repository dhruvdev01/pig-js, pull requests merged in 2022-10, with the labels that each got.

#2 comments added
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#4 Update index.html
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#5 readme-update
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#6 Color_ changed_from grey_to_black
  style2.css
Labels: documentation, hacktoberfest-accepted, hacktoberfest
